.TH xfs_healer_start 8
.SH NAME
xfs_healer_start \- starts xfs_healer instances
.SH SYNOPSIS
.B xfs_healer_start
[
.B OPTIONS
]
.br
.B xfs_healer \-V
.SH DESCRIPTION
.B xfs_healer_start
starts the xfs_healer service whenever the kernel mounts an XFS filesystem in
the current mount namespace.
.PP
.B WARNING!
This program is
.BR EXPERIMENTAL ","
which means that its behavior and interface
could change at any time!

Normally this program runs as a systemd service.

.SH OPTIONS
.TP
.B \-\-supported
Check if the kernel supports listening for mount events.
Exits with 0 if it does, and non-zero if not.
.TP
.BI "\-\-mountns " path
Monitor the given mount namespace.
Defaults to the mount namespace associated with the process itself.
.TP
.BI \-V
Prints the version number and exit.
.SH SEE ALSO
.BR xfs_healer (8).
