#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2018 Oracle.  All Rights Reserved.
# Author: Darrick J. Wong <djwong@kernel.org>

# Email logs of failed xfs_scrub unit runs

recipient="$1"
test -z "${recipient}" && exit 0
mntpoint="$2"
test -z "${mntpoint}" && exit 0
hostname="$(hostname -f 2>/dev/null)"
test -z "${hostname}" && hostname="${HOSTNAME}"

mailer="$(command -v sendmail)"
if [ ! -x "${mailer}" ]; then
	echo "${mailer}: Mailer program not found."
	exit 1
fi

mntpoint_esc="$(systemd-escape --path "${mntpoint}")"

(cat << ENDL
To: $1
From: <xfs_scrub@${hostname}>
Subject: xfs_scrub failure on ${mntpoint}

So sorry, the automatic xfs_scrub of ${mntpoint} on ${hostname} failed.

A log of what happened follows:
ENDL
systemctl status --full --lines 4294967295 "xfs_scrub@${mntpoint_esc}") | "${mailer}" -t -i
exit "${PIPESTATUS[1]}"
