#!/bin/sh

set -e

# dh_installsystemd doesn't handle template services even if we supply a
# default instance, so we'll install it here.
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	/bin/systemctl disable xfs_healer@.service || true
fi

#DEBHELPER#

exit 0
